 export let EmployeeData=[
    {
    id:'01',
    first_name:"Rahul",
    last_name:"Singh",
    age:"20"
    },
    {
    id:'02',
    first_name:"Susthir",
    last_name:"Nahak",
    age:"25"
    },
    {
    id:'03',
    first_name:"Vinod",
    last_name:"Gupta",
    age:"28"
    }
    ]